## This is the configuration file for Headroom.
## See https://github.com/vaclavsvejcar/headroom for more details.

version: 0.4.0.0

run-mode: replace

source-paths:
  - app
  - src

excluded-paths: []

template-paths:
  - headroom-templates

variables:
  author: Vaclav Svejcar
  email: vaclav.svejcar@gmail.com
  year: 2020-2022

license-headers:
  haskell:
    put-after: ["^{-#"]
    put-before: ["^module"]
    margin-top-code: 1
    margin-bottom-code: 1

post-process:
  update-copyright:
    enabled: true
    config:
      selected-authors-only: ["{{ author }}"]
