name: vcs-ignore
version: 0.0.2.0
homepage: https://github.com/vaclavsvejcar/vcs-ignore
license: BSD-3-Clause
license-file: LICENSE
github: vaclavsvejcar/vcs-ignore
author: Vaclav Svejcar
maintainer: vaclav.svejcar@gmail.com
copyright: Copyright (c) 2020-2021 Vaclav Svejcar
category: Development

synopsis: Library for handling files ignored by VCS systems.
description: >
  vcs-ignore is small Haskell library used to find, check and process files
  ignored by selected VCS.


extra-source-files:
  - README.md
  - CHANGELOG.md
  - test-data/fake-git-repo/.gitignore
  - test-data/fake-git-repo/a/*
  - test-data/fake-git-repo/a/.gitignore
  - test-data/fake-git-repo/a/b/*
  - test-data/fake-git-repo/a/b/.gitignore
  - test-data/list-files/*
  - test-data/list-files/dir1/*
  - test-data/list-files/dir1/dir2/*

dependencies:
  - base >= 4.7 && < 5
  - containers
  - directory
  - exceptions
  - filepath
  - text

ghc-options:
  - -optP-Wno-nonportable-include-path
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Werror=incomplete-patterns

library:
  generated-other-modules: Paths_vcs_ignore
  source-dirs: src
  dependencies:
    - Glob
    - text

executables:
  ignore:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - optparse-applicative
      - vcs-ignore

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - vcs-ignore
    build-tools: hspec-discover
  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - doctest
